# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class Account < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :address, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('address') } }
      field :metadata, T.nilable(T::Hash[Symbol, Object]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('metadata') } }
      field :type, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('type') } }

      sig { params(address: String, metadata: T.nilable(T::Hash[Symbol, Object]), type: T.nilable(String)).void }
      def initialize(address: nil, metadata: nil, type: nil)
        @address = address
        @metadata = metadata
        @type = type
      end
    end
  end
end
