# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class AccountWithVolumesAndBalances < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :address, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('address') } }
      field :balances, T.nilable(T::Hash[Symbol, Integer]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('balances') } }
      field :metadata, T.nilable(T::Hash[Symbol, Object]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('metadata') } }
      field :type, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('type') } }
      field :volumes, T.nilable(T::Hash[Symbol, T::Hash[Symbol, Integer]]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('volumes') } }

      sig { params(address: String, balances: T.nilable(T::Hash[Symbol, Integer]), metadata: T.nilable(T::Hash[Symbol, Object]), type: T.nilable(String), volumes: T.nilable(T::Hash[Symbol, T::Hash[Symbol, Integer]])).void }
      def initialize(address: nil, balances: nil, metadata: nil, type: nil, volumes: nil)
        @address = address
        @balances = balances
        @metadata = metadata
        @type = type
        @volumes = volumes
      end
    end
  end
end
