# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class BalanceWithAssets < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :assets, T::Hash[Symbol, Float], { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('assets') } }
      field :name, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('name') } }

      sig { params(assets: T::Hash[Symbol, Float], name: String).void }
      def initialize(assets: nil, name: nil)
        @assets = assets
        @name = name
      end
    end
  end
end
