# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/webhooksconfig'

module OpenApiSDK
  module Shared# 2 - Config created successfully.
    class ConfigResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :data, WebhooksConfig, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('data') } }

      sig { params(data: WebhooksConfig).void }
      def initialize(data: nil)
        @data = data
      end
    end
  end
end
