# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/config'

module OpenApiSDK
  module Shared
    class ConfigInfo < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :config, Config, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('config') } }
      field :server, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('server') } }
      field :version, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('version') } }

      sig { params(config: Config, server: String, version: String).void }
      def initialize(config: nil, server: nil, version: nil)
        @config = config
        @server = server
        @version = version
      end
    end
  end
end
