# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class ConfigChangeSecret < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :secret, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('secret') } }

      sig { params(secret: T.nilable(String)).void }
      def initialize(secret: nil)
        @secret = secret
      end
    end
  end
end
