# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class ConfigUser < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :endpoint, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('endpoint') } }
      field :event_types, T::Array[String], { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('eventTypes') } }
      field :secret, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('secret') } }

      sig { params(endpoint: String, event_types: T::Array[String], secret: T.nilable(String)).void }
      def initialize(endpoint: nil, event_types: nil, secret: nil)
        @endpoint = endpoint
        @event_types = event_types
        @secret = secret
      end
    end
  end
end
