# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class ConfirmHoldRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Define the amount to transfer.
      field :amount, T.nilable(Integer), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('amount') } }      # Define a final confirmation. Remaining funds will be returned to the wallet.
      field :final, T.nilable(T::Boolean), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('final') } }

      sig { params(amount: T.nilable(Integer), final: T.nilable(T::Boolean)).void }
      def initialize(amount: nil, final: nil)
        @amount = amount
        @final = final
      end
    end
  end
end
