# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    # ConnectorEnum - The name of the connector.
    class ConnectorEnum < T::Enum
      enums do
        STRIPE = new('STRIPE')
        DUMMY_PAY = new('DUMMY-PAY')
        WISE = new('WISE')
        MODULR = new('MODULR')
        CURRENCY_CLOUD = new('CURRENCY-CLOUD')
        BANKING_CIRCLE = new('BANKING-CIRCLE')
      end
    end

  end
end
