# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class Contract < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :expr, T::Hash[Symbol, Object], { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('expr') } }
      field :account, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('account') } }

      sig { params(expr: T::Hash[Symbol, Object], account: T.nilable(String)).void }
      def initialize(expr: nil, account: nil)
        @expr = expr
        @account = account
      end
    end
  end
end
