# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class CreateScopeRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :label, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('label') } }
      field :metadata, T.nilable(T::Hash[Symbol, Object]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('metadata') } }

      sig { params(label: String, metadata: T.nilable(T::Hash[Symbol, Object])).void }
      def initialize(label: nil, metadata: nil)
        @label = label
        @metadata = metadata
      end
    end
  end
end
