# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class CreateSecretRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :name, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('name') } }
      field :metadata, T.nilable(T::Hash[Symbol, Object]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('metadata') } }

      sig { params(name: String, metadata: T.nilable(T::Hash[Symbol, Object])).void }
      def initialize(name: nil, metadata: nil)
        @name = name
        @metadata = metadata
      end
    end
  end
end
