# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/hold'

module OpenApiSDK
  module Shared# 2 - Wallet successfully debited as a pending hold
    class DebitWalletResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :data, Hold, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('data') } }

      sig { params(data: Hold).void }
      def initialize(data: nil)
        @data = data
      end
    end
  end
end
