# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class DummyPayConfig < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :directory, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('directory') } }      # The frequency at which the connector will create new payment objects in the directory
      field :file_generation_period, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('fileGenerationPeriod') } }      # The frequency at which the connector will try to fetch new payment objects from the directory
      field :file_polling_period, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('filePollingPeriod') } }

      sig { params(directory: String, file_generation_period: T.nilable(String), file_polling_period: T.nilable(String)).void }
      def initialize(directory: nil, file_generation_period: nil, file_polling_period: nil)
        @directory = directory
        @file_generation_period = file_generation_period
        @file_polling_period = file_polling_period
      end
    end
  end
end
