# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared

    class ErrorsEnumEnum < T::Enum
      enums do
        INTERNAL = new('INTERNAL')
        INSUFFICIENT_FUND = new('INSUFFICIENT_FUND')
        VALIDATION = new('VALIDATION')
        CONFLICT = new('CONFLICT')
        NO_SCRIPT = new('NO_SCRIPT')
        COMPILATION_FAILED = new('COMPILATION_FAILED')
        METADATA_OVERRIDE = new('METADATA_OVERRIDE')
      end
    end

  end
end
