# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class LedgerAccountSubject < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :identifier, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('identifier') } }
      field :type, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('type') } }

      sig { params(identifier: String, type: String).void }
      def initialize(identifier: nil, type: nil)
        @identifier = identifier
        @type = type
      end
    end
  end
end
