# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class Mapping < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :contracts, T::Array[Contract], { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('contracts') } }

      sig { params(contracts: T::Array[Contract]).void }
      def initialize(contracts: nil)
        @contracts = contracts
      end
    end
  end
end
