# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class ModulrConfig < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :api_key, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('apiKey') } }
      field :api_secret, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('apiSecret') } }
      field :endpoint, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('endpoint') } }

      sig { params(api_key: String, api_secret: String, endpoint: T.nilable(String)).void }
      def initialize(api_key: nil, api_secret: nil, endpoint: nil)
        @api_key = api_key
        @api_secret = api_secret
        @endpoint = endpoint
      end
    end
  end
end
