# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class Monetary < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # The amount of the monetary value.
      field :amount, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('amount') } }      # The asset of the monetary value.
      field :asset, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('asset') } }

      sig { params(amount: Integer, asset: String).void }
      def initialize(amount: nil, asset: nil)
        @amount = amount
        @asset = asset
      end
    end
  end
end
