# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/paymentmetadatachangelog'

module OpenApiSDK
  module Shared
    class PaymentMetadata < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :key, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('key') } }
      field :value, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('value') } }
      field :changelog, T.nilable(PaymentMetadataChangelog), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('changelog') } }

      sig { params(key: String, value: String, changelog: T.nilable(PaymentMetadataChangelog)).void }
      def initialize(key: nil, value: nil, changelog: nil)
        @key = key
        @value = value
        @changelog = changelog
      end
    end
  end
end
