# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared

    class PaymentStatusEnum < T::Enum
      enums do
        PENDING = new('PENDING')
        ACTIVE = new('ACTIVE')
        TERMINATED = new('TERMINATED')
        FAILED = new('FAILED')
      end
    end

  end
end
