# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class Posting < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :amount, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('amount') } }
      field :asset, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('asset') } }
      field :destination, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('destination') } }
      field :source, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('source') } }

      sig { params(amount: Integer, asset: String, destination: String, source: String).void }
      def initialize(amount: nil, asset: nil, destination: nil, source: nil)
        @amount = amount
        @asset = asset
        @destination = destination
        @source = source
      end
    end
  end
end
