# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class PostTransactionScript < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :plain, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('plain') } }
      field :vars, T.nilable(T::Hash[Symbol, Object]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('vars') } }

      sig { params(plain: String, vars: T.nilable(T::Hash[Symbol, Object])).void }
      def initialize(plain: nil, vars: nil)
        @plain = plain
        @vars = vars
      end
    end
# 2 - The request body must contain at least one of the following objects:
#   - `postings`: suitable for simple transactions
#   - `script`: enabling more complex transactions with Numscript
# 
    class PostTransaction < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :metadata, T.nilable(T::Hash[Symbol, Object]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('metadata') } }
      field :postings, T.nilable(T::Array[Posting]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('postings') } }
      field :reference, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('reference') } }
      field :script, T.nilable(PostTransactionScript), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('script') } }
      field :timestamp, T.nilable(DateTime), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('timestamp'), 'decoder': Utils.datetime_from_iso_format(true) } }

      sig { params(metadata: T.nilable(T::Hash[Symbol, Object]), postings: T.nilable(T::Array[Posting]), reference: T.nilable(String), script: T.nilable(PostTransactionScript), timestamp: T.nilable(DateTime)).void }
      def initialize(metadata: nil, postings: nil, reference: nil, script: nil, timestamp: nil)
        @metadata = metadata
        @postings = postings
        @reference = reference
        @script = script
        @timestamp = timestamp
      end
    end
  end
end
