# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class Security < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :authorization, String, { 'security': { 'scheme': true, 'type': 'oauth2', 'field_name': 'Authorization' } }

      sig { params(authorization: String).void }
      def initialize(authorization: nil)
        @authorization = authorization
      end
    end
  end
end
