# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared# 2 - Server information
    class ServerInfo < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :version, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('version') } }

      sig { params(version: String).void }
      def initialize(version: nil)
        @version = version
      end
    end
  end
end
