# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class Stats < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :accounts, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('accounts') } }
      field :transactions, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('transactions') } }

      sig { params(accounts: Integer, transactions: Integer).void }
      def initialize(accounts: nil, transactions: nil)
        @accounts = accounts
        @transactions = transactions
      end
    end
  end
end
