# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/paymentstatus_enum'

module OpenApiSDK
  module Shared
    class TaskWiseDescriptor < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :key, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('key') } }
      field :name, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('name') } }
      field :profile_id, T.nilable(Integer), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('profileID') } }

      sig { params(key: T.nilable(String), name: T.nilable(String), profile_id: T.nilable(Integer)).void }
      def initialize(key: nil, name: nil, profile_id: nil)
        @key = key
        @name = name
        @profile_id = profile_id
      end
    end

    class TaskWise < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :connector_id, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('connectorId') } }
      field :created_at, DateTime, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('createdAt'), 'decoder': Utils.datetime_from_iso_format(false) } }
      field :descriptor, TaskWiseDescriptor, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('descriptor') } }
      field :id, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('id') } }
      field :state, T::Hash[Symbol, Object], { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('state') } }
      field :status, PaymentStatusEnum, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Shared::PaymentStatusEnum, false) } }
      field :updated_at, DateTime, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('updatedAt'), 'decoder': Utils.datetime_from_iso_format(false) } }
      field :error, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('error') } }

      sig { params(connector_id: String, created_at: DateTime, descriptor: TaskWiseDescriptor, id: String, state: T::Hash[Symbol, Object], status: PaymentStatusEnum, updated_at: DateTime, error: T.nilable(String)).void }
      def initialize(connector_id: nil, created_at: nil, descriptor: nil, id: nil, state: nil, status: nil, updated_at: nil, error: nil)
        @connector_id = connector_id
        @created_at = created_at
        @descriptor = descriptor
        @id = id
        @state = state
        @status = status
        @updated_at = updated_at
        @error = error
      end
    end
  end
end
