# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class UpdateClientRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :name, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('name') } }
      field :description, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('description') } }
      field :metadata, T.nilable(T::Hash[Symbol, Object]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('metadata') } }
      field :post_logout_redirect_uris, T.nilable(T::Array[String]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('postLogoutRedirectUris') } }
      field :public, T.nilable(T::Boolean), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('public') } }
      field :redirect_uris, T.nilable(T::Array[String]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('redirectUris') } }
      field :trusted, T.nilable(T::Boolean), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('trusted') } }

      sig { params(name: String, description: T.nilable(String), metadata: T.nilable(T::Hash[Symbol, Object]), post_logout_redirect_uris: T.nilable(T::Array[String]), public: T.nilable(T::Boolean), redirect_uris: T.nilable(T::Array[String]), trusted: T.nilable(T::Boolean)).void }
      def initialize(name: nil, description: nil, metadata: nil, post_logout_redirect_uris: nil, public: nil, redirect_uris: nil, trusted: nil)
        @name = name
        @description = description
        @metadata = metadata
        @post_logout_redirect_uris = post_logout_redirect_uris
        @public = public
        @redirect_uris = redirect_uris
        @trusted = trusted
      end
    end
  end
end
