# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class User < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :email, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('email') } }
      field :id, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('id') } }
      field :subject, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('subject') } }

      sig { params(email: T.nilable(String), id: T.nilable(String), subject: T.nilable(String)).void }
      def initialize(email: nil, id: nil, subject: nil)
        @email = email
        @id = id
        @subject = subject
      end
    end
  end
end
