# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class Volume < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :input, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('input') } }
      field :output, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('output') } }
      field :balance, T.nilable(Integer), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('balance') } }

      sig { params(input: Integer, output: Integer, balance: T.nilable(Integer)).void }
      def initialize(input: nil, output: nil, balance: nil)
        @input = input
        @output = output
        @balance = balance
      end
    end
  end
end
