# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class WalletsVolume < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :balance, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('balance') } }
      field :input, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('input') } }
      field :output, Integer, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('output') } }

      sig { params(balance: Integer, input: Integer, output: Integer).void }
      def initialize(balance: nil, input: nil, output: nil)
        @balance = balance
        @input = input
        @output = output
      end
    end
  end
end
