# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/workflowconfig'

module OpenApiSDK
  module Shared
    class Workflow < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :config, WorkflowConfig, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('config') } }
      field :created_at, DateTime, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('createdAt'), 'decoder': Utils.datetime_from_iso_format(false) } }
      field :id, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('id') } }
      field :updated_at, DateTime, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('updatedAt'), 'decoder': Utils.datetime_from_iso_format(false) } }

      sig { params(config: WorkflowConfig, created_at: DateTime, id: String, updated_at: DateTime).void }
      def initialize(config: nil, created_at: nil, id: nil, updated_at: nil)
        @config = config
        @created_at = created_at
        @id = id
        @updated_at = updated_at
      end
    end
  end
end
