# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    class WorkflowConfig < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :stages, T::Array[T::Hash[Symbol, Object]], { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('stages') } }

      sig { params(stages: T::Array[T::Hash[Symbol, Object]]).void }
      def initialize(stages: nil)
        @stages = stages
      end
    end
  end
end
