# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/errorresponse'

module OpenApiSDK
  module Operations
    class AddMetadataToAccountRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Exact address of the account. It must match the following regular expressions pattern:
      # ```
      # ^\w+(:\w+)*$
      # ```
      # 
      field :address, String, { 'path_param': { 'field_name': 'address', 'style': 'simple', 'explode': false } }      # Name of the ledger.
      field :ledger, String, { 'path_param': { 'field_name': 'ledger', 'style': 'simple', 'explode': false } }      # metadata
      field :request_body, T::Hash[Symbol, Object], { 'request': { 'media_type': 'application/json' } }

      sig { params(address: String, ledger: String, request_body: T::Hash[Symbol, Object]).void }
      def initialize(address: nil, ledger: nil, request_body: nil)
        @address = address
        @ledger = ledger
        @request_body = request_body
      end
    end

    class AddMetadataToAccountResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Error
      field :error_response, T.nilable(Shared::ErrorResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, error_response: T.nilable(Shared::ErrorResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, error_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @error_response = error_response
        @raw_response = raw_response
      end
    end
  end
end
