# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/configchangesecret'
require_relative '../shared/configresponse'

module OpenApiSDK
  module Operations
    class ChangeConfigSecretRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Config ID
      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
      field :config_change_secret, T.nilable(Shared::ConfigChangeSecret), { 'request': { 'media_type': 'application/json' } }

      sig { params(id: String, config_change_secret: T.nilable(Shared::ConfigChangeSecret)).void }
      def initialize(id: nil, config_change_secret: nil)
        @id = id
        @config_change_secret = config_change_secret
      end
    end

    class ChangeConfigSecretResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Secret successfully changed.
      field :config_response, T.nilable(Shared::ConfigResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, config_response: T.nilable(Shared::ConfigResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, config_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @config_response = config_response
        @raw_response = raw_response
      end
    end
  end
end
