# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/confirmholdrequest'
require_relative '../shared/walletserrorresponse'

module OpenApiSDK
  module Operations
    class ConfirmHoldRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :hold_id, String, { 'path_param': { 'field_name': 'hold_id', 'style': 'simple', 'explode': false } }
      field :confirm_hold_request, T.nilable(Shared::ConfirmHoldRequest), { 'request': { 'media_type': 'application/json' } }

      sig { params(hold_id: String, confirm_hold_request: T.nilable(Shared::ConfirmHoldRequest)).void }
      def initialize(hold_id: nil, confirm_hold_request: nil)
        @hold_id = hold_id
        @confirm_hold_request = confirm_hold_request
      end
    end

    class ConfirmHoldResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)      # Error
      field :wallets_error_response, T.nilable(Shared::WalletsErrorResponse)

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), wallets_error_response: T.nilable(Shared::WalletsErrorResponse)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, wallets_error_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @wallets_error_response = wallets_error_response
      end
    end
  end
end
