# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Operations
    class ConnectorsStripeTransferResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)      # OK
      field :stripe_transfer_response, T.nilable(T::Hash[Symbol, Object])

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), stripe_transfer_response: T.nilable(T::Hash[Symbol, Object])).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, stripe_transfer_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @stripe_transfer_response = stripe_transfer_response
      end
    end
  end
end
