# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/createclientresponse'

module OpenApiSDK
  module Operations
    class CreateClientResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Client created
      field :create_client_response, T.nilable(Shared::CreateClientResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, create_client_response: T.nilable(Shared::CreateClientResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, create_client_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @create_client_response = create_client_response
        @raw_response = raw_response
      end
    end
  end
end
