# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/debitwalletrequest'
require_relative '../shared/debitwalletresponse'
require_relative '../shared/walletserrorresponse'

module OpenApiSDK
  module Operations
    class DebitWalletRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
      field :debit_wallet_request, T.nilable(Shared::DebitWalletRequest), { 'request': { 'media_type': 'application/json' } }

      sig { params(id: String, debit_wallet_request: T.nilable(Shared::DebitWalletRequest)).void }
      def initialize(id: nil, debit_wallet_request: nil)
        @id = id
        @debit_wallet_request = debit_wallet_request
      end
    end

    class DebitWalletResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Wallet successfully debited as a pending hold
      field :debit_wallet_response, T.nilable(Shared::DebitWalletResponse)
      field :raw_response, T.nilable(Faraday::Response)      # Error
      field :wallets_error_response, T.nilable(Shared::WalletsErrorResponse)

      sig { params(content_type: String, status_code: Integer, debit_wallet_response: T.nilable(Shared::DebitWalletResponse), raw_response: T.nilable(Faraday::Response), wallets_error_response: T.nilable(Shared::WalletsErrorResponse)).void }
      def initialize(content_type: nil, status_code: nil, debit_wallet_response: nil, raw_response: nil, wallets_error_response: nil)
        @content_type = content_type
        @status_code = status_code
        @debit_wallet_response = debit_wallet_response
        @raw_response = raw_response
        @wallets_error_response = wallets_error_response
      end
    end
  end
end
