# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Operations
    class DeleteSecretRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Client ID
      field :client_id, String, { 'path_param': { 'field_name': 'clientId', 'style': 'simple', 'explode': false } }      # Secret ID
      field :secret_id, String, { 'path_param': { 'field_name': 'secretId', 'style': 'simple', 'explode': false } }

      sig { params(client_id: String, secret_id: String).void }
      def initialize(client_id: nil, secret_id: nil)
        @client_id = client_id
        @secret_id = secret_id
      end
    end

    class DeleteSecretResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
      end
    end
  end
end
