# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/accountresponse'
require_relative '../shared/errorresponse'

module OpenApiSDK
  module Operations
    class GetAccountRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Exact address of the account. It must match the following regular expressions pattern:
      # ```
      # ^\w+(:\w+)*$
      # ```
      # 
      field :address, String, { 'path_param': { 'field_name': 'address', 'style': 'simple', 'explode': false } }      # Name of the ledger.
      field :ledger, String, { 'path_param': { 'field_name': 'ledger', 'style': 'simple', 'explode': false } }

      sig { params(address: String, ledger: String).void }
      def initialize(address: nil, ledger: nil)
        @address = address
        @ledger = ledger
      end
    end

    class GetAccountResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # OK
      field :account_response, T.nilable(Shared::AccountResponse)      # Error
      field :error_response, T.nilable(Shared::ErrorResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, account_response: T.nilable(Shared::AccountResponse), error_response: T.nilable(Shared::ErrorResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, account_response: nil, error_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @account_response = account_response
        @error_response = error_response
        @raw_response = raw_response
      end
    end
  end
end
