# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/getbalanceresponse'
require_relative '../shared/walletserrorresponse'

module OpenApiSDK
  module Operations
    class GetBalanceRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :balance_name, String, { 'path_param': { 'field_name': 'balanceName', 'style': 'simple', 'explode': false } }
      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

      sig { params(balance_name: String, id: String).void }
      def initialize(balance_name: nil, id: nil)
        @balance_name = balance_name
        @id = id
      end
    end

    class GetBalanceResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Balance summary
      field :get_balance_response, T.nilable(Shared::GetBalanceResponse)
      field :raw_response, T.nilable(Faraday::Response)      # Error
      field :wallets_error_response, T.nilable(Shared::WalletsErrorResponse)

      sig { params(content_type: String, status_code: Integer, get_balance_response: T.nilable(Shared::GetBalanceResponse), raw_response: T.nilable(Faraday::Response), wallets_error_response: T.nilable(Shared::WalletsErrorResponse)).void }
      def initialize(content_type: nil, status_code: nil, get_balance_response: nil, raw_response: nil, wallets_error_response: nil)
        @content_type = content_type
        @status_code = status_code
        @get_balance_response = get_balance_response
        @raw_response = raw_response
        @wallets_error_response = wallets_error_response
      end
    end
  end
end
