# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/aggregatebalancesresponse'
require_relative '../shared/errorresponse'

module OpenApiSDK
  module Operations
    class GetBalancesAggregatedRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Name of the ledger.
      field :ledger, String, { 'path_param': { 'field_name': 'ledger', 'style': 'simple', 'explode': false } }      # Filter balances involving given account, either as source or destination.
      field :address, T.nilable(String), { 'query_param': { 'field_name': 'address', 'style': 'form', 'explode': true } }

      sig { params(ledger: String, address: T.nilable(String)).void }
      def initialize(ledger: nil, address: nil)
        @ledger = ledger
        @address = address
      end
    end

    class GetBalancesAggregatedResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # OK
      field :aggregate_balances_response, T.nilable(Shared::AggregateBalancesResponse)      # Error
      field :error_response, T.nilable(Shared::ErrorResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, aggregate_balances_response: T.nilable(Shared::AggregateBalancesResponse), error_response: T.nilable(Shared::ErrorResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, aggregate_balances_response: nil, error_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @aggregate_balances_response = aggregate_balances_response
        @error_response = error_response
        @raw_response = raw_response
      end
    end
  end
end
