# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/connector_enum'
require_relative '../shared/taskresponse'

module OpenApiSDK
  module Operations
    class GetConnectorTaskRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # The name of the connector.
      field :connector, Shared::ConnectorEnum, { 'path_param': { 'field_name': 'connector', 'style': 'simple', 'explode': false } }      # The task ID.
      field :task_id, String, { 'path_param': { 'field_name': 'taskId', 'style': 'simple', 'explode': false } }

      sig { params(connector: Shared::ConnectorEnum, task_id: String).void }
      def initialize(connector: nil, task_id: nil)
        @connector = connector
        @task_id = task_id
      end
    end

    class GetConnectorTaskResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)      # OK
      field :task_response, T.nilable(Shared::TaskResponse)

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), task_response: T.nilable(Shared::TaskResponse)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, task_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @task_response = task_response
      end
    end
  end
end
