# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/getholdresponse'
require_relative '../shared/walletserrorresponse'

module OpenApiSDK
  module Operations
    class GetHoldRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # The hold ID
      field :hold_id, String, { 'path_param': { 'field_name': 'holdID', 'style': 'simple', 'explode': false } }

      sig { params(hold_id: String).void }
      def initialize(hold_id: nil)
        @hold_id = hold_id
      end
    end

    class GetHoldResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Holds
      field :get_hold_response, T.nilable(Shared::GetHoldResponse)
      field :raw_response, T.nilable(Faraday::Response)      # Error
      field :wallets_error_response, T.nilable(Shared::WalletsErrorResponse)

      sig { params(content_type: String, status_code: Integer, get_hold_response: T.nilable(Shared::GetHoldResponse), raw_response: T.nilable(Faraday::Response), wallets_error_response: T.nilable(Shared::WalletsErrorResponse)).void }
      def initialize(content_type: nil, status_code: nil, get_hold_response: nil, raw_response: nil, wallets_error_response: nil)
        @content_type = content_type
        @status_code = status_code
        @get_hold_response = get_hold_response
        @raw_response = raw_response
        @wallets_error_response = wallets_error_response
      end
    end
  end
end
