# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/paymentresponse'

module OpenApiSDK
  module Operations
    class GetPaymentRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # The payment ID.
      field :payment_id, String, { 'path_param': { 'field_name': 'paymentId', 'style': 'simple', 'explode': false } }

      sig { params(payment_id: String).void }
      def initialize(payment_id: nil)
        @payment_id = payment_id
      end
    end

    class GetPaymentResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # OK
      field :payment_response, T.nilable(Shared::PaymentResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, payment_response: T.nilable(Shared::PaymentResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, payment_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @payment_response = payment_response
        @raw_response = raw_response
      end
    end
  end
end
