# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/getwalletresponse'
require_relative '../shared/walletserrorresponse'

module OpenApiSDK
  module Operations
    class GetWalletRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

      sig { params(id: String).void }
      def initialize(id: nil)
        @id = id
      end
    end

    class GetWalletResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Wallet
      field :get_wallet_response, T.nilable(Shared::GetWalletResponse)
      field :raw_response, T.nilable(Faraday::Response)      # Error
      field :wallets_error_response, T.nilable(Shared::WalletsErrorResponse)

      sig { params(content_type: String, status_code: Integer, get_wallet_response: T.nilable(Shared::GetWalletResponse), raw_response: T.nilable(Faraday::Response), wallets_error_response: T.nilable(Shared::WalletsErrorResponse)).void }
      def initialize(content_type: nil, status_code: nil, get_wallet_response: nil, raw_response: nil, wallets_error_response: nil)
        @content_type = content_type
        @status_code = status_code
        @get_wallet_response = get_wallet_response
        @raw_response = raw_response
        @wallets_error_response = wallets_error_response
      end
    end
  end
end
