# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/configresponse'

module OpenApiSDK
  module Operations
    class InsertConfigResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Config created successfully.
      field :config_response, T.nilable(Shared::ConfigResponse)      # Bad Request
      field :insert_config_400_text_plain_string, T.nilable(String)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, config_response: T.nilable(Shared::ConfigResponse), insert_config_400_text_plain_string: T.nilable(String), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, config_response: nil, insert_config_400_text_plain_string: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @config_response = config_response
        @insert_config_400_text_plain_string = insert_config_400_text_plain_string
        @raw_response = raw_response
      end
    end
  end
end
