# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/listwalletsresponse'

module OpenApiSDK
  module Operations
    class ListWalletsRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Parameter used in pagination requests.
      # Set to the value of next for the next page of results.
      # Set to the value of previous for the previous page of results.
      # No other parameters can be set when the pagination token is set.
      # 
      field :cursor, T.nilable(String), { 'query_param': { 'field_name': 'cursor', 'style': 'form', 'explode': true } }      # Filter wallets by metadata key value pairs. Nested objects can be used as seen in the example below.
      field :metadata, T.nilable(T::Hash[Symbol, Object]), { 'query_param': { 'field_name': 'metadata', 'style': 'deepObject', 'explode': true } }      # Filter on wallet name
      field :name, T.nilable(String), { 'query_param': { 'field_name': 'name', 'style': 'form', 'explode': true } }      # The maximum number of results to return per page
      field :page_size, T.nilable(Integer), { 'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': true } }

      sig { params(cursor: T.nilable(String), metadata: T.nilable(T::Hash[Symbol, Object]), name: T.nilable(String), page_size: T.nilable(Integer)).void }
      def initialize(cursor: nil, metadata: nil, name: nil, page_size: nil)
        @cursor = cursor
        @metadata = metadata
        @name = name
        @page_size = page_size
      end
    end

    class ListWalletsResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # OK
      field :list_wallets_response, T.nilable(Shared::ListWalletsResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, list_wallets_response: T.nilable(Shared::ListWalletsResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, list_wallets_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @list_wallets_response = list_wallets_response
        @raw_response = raw_response
      end
    end
  end
end
