# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/errorresponse'
require_relative '../shared/logscursorresponse'

module OpenApiSDK
  module Operations
    class ListLogsRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Name of the ledger.
      field :ledger, String, { 'path_param': { 'field_name': 'ledger', 'style': 'simple', 'explode': false } }      # Pagination cursor, will return the logs after a given ID. (in descending order).
      field :after, T.nilable(String), { 'query_param': { 'field_name': 'after', 'style': 'form', 'explode': true } }      # Parameter used in pagination requests. Maximum page size is set to 15.
      # Set to the value of next for the next page of results.
      # Set to the value of previous for the previous page of results.
      # No other parameters can be set when this parameter is set.
      # 
      field :cursor, T.nilable(String), { 'query_param': { 'field_name': 'cursor', 'style': 'form', 'explode': true } }      # Filter transactions that occurred before this timestamp.
      # The format is RFC3339 and is exclusive (for example, "2023-01-02T15:04:01Z" excludes the first second of 4th minute).
      # 
      field :end_time, T.nilable(DateTime), { 'query_param': { 'field_name': 'endTime', 'style': 'form', 'explode': true } }      # Filter transactions that occurred before this timestamp.
      # The format is RFC3339 and is exclusive (for example, "2023-01-02T15:04:01Z" excludes the first second of 4th minute).
      # Deprecated, please use `endTime` instead.
      # 
      field :end_time_deprecated, T.nilable(DateTime), { 'query_param': { 'field_name': 'end_time', 'style': 'form', 'explode': true } }      # The maximum number of results to return per page.
      # 
      field :page_size, T.nilable(Integer), { 'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': true } }      # The maximum number of results to return per page.
      # Deprecated, please use `pageSize` instead.
      # 
      field :page_size_deprecated, T.nilable(Integer), { 'query_param': { 'field_name': 'page_size', 'style': 'form', 'explode': true } }      # Parameter used in pagination requests. Maximum page size is set to 15.
      # Set to the value of next for the next page of results.
      # Set to the value of previous for the previous page of results.
      # No other parameters can be set when this parameter is set.
      # Deprecated, please use `cursor` instead.
      # 
      field :pagination_token, T.nilable(String), { 'query_param': { 'field_name': 'pagination_token', 'style': 'form', 'explode': true } }      # Filter transactions that occurred after this timestamp.
      # The format is RFC3339 and is inclusive (for example, "2023-01-02T15:04:01Z" includes the first second of 4th minute).
      # 
      field :start_time, T.nilable(DateTime), { 'query_param': { 'field_name': 'startTime', 'style': 'form', 'explode': true } }      # Filter transactions that occurred after this timestamp.
      # The format is RFC3339 and is inclusive (for example, "2023-01-02T15:04:01Z" includes the first second of 4th minute).
      # Deprecated, please use `startTime` instead.
      # 
      field :start_time_deprecated, T.nilable(DateTime), { 'query_param': { 'field_name': 'start_time', 'style': 'form', 'explode': true } }

      sig { params(ledger: String, after: T.nilable(String), cursor: T.nilable(String), end_time: T.nilable(DateTime), end_time_deprecated: T.nilable(DateTime), page_size: T.nilable(Integer), page_size_deprecated: T.nilable(Integer), pagination_token: T.nilable(String), start_time: T.nilable(DateTime), start_time_deprecated: T.nilable(DateTime)).void }
      def initialize(ledger: nil, after: nil, cursor: nil, end_time: nil, end_time_deprecated: nil, page_size: nil, page_size_deprecated: nil, pagination_token: nil, start_time: nil, start_time_deprecated: nil)
        @ledger = ledger
        @after = after
        @cursor = cursor
        @end_time = end_time
        @end_time_deprecated = end_time_deprecated
        @page_size = page_size
        @page_size_deprecated = page_size_deprecated
        @pagination_token = pagination_token
        @start_time = start_time
        @start_time_deprecated = start_time_deprecated
      end
    end

    class ListLogsResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Error
      field :error_response, T.nilable(Shared::ErrorResponse)      # OK
      field :logs_cursor_response, T.nilable(Shared::LogsCursorResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, error_response: T.nilable(Shared::ErrorResponse), logs_cursor_response: T.nilable(Shared::LogsCursorResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, error_response: nil, logs_cursor_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @error_response = error_response
        @logs_cursor_response = logs_cursor_response
        @raw_response = raw_response
      end
    end
  end
end
