# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/paymentscursor'

module OpenApiSDK
  module Operations
    class ListPaymentsRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Parameter used in pagination requests. Maximum page size is set to 15.
      # Set to the value of next for the next page of results.
      # Set to the value of previous for the previous page of results.
      # No other parameters can be set when this parameter is set.
      # 
      field :cursor, T.nilable(String), { 'query_param': { 'field_name': 'cursor', 'style': 'form', 'explode': true } }      # The maximum number of results to return per page.
      # 
      field :page_size, T.nilable(Integer), { 'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': true } }      # Fields used to sort payments (default is date:desc).
      field :sort, T.nilable(T::Array[String]), { 'query_param': { 'field_name': 'sort', 'style': 'form', 'explode': true } }

      sig { params(cursor: T.nilable(String), page_size: T.nilable(Integer), sort: T.nilable(T::Array[String])).void }
      def initialize(cursor: nil, page_size: nil, sort: nil)
        @cursor = cursor
        @page_size = page_size
        @sort = sort
      end
    end

    class ListPaymentsResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # OK
      field :payments_cursor, T.nilable(Shared::PaymentsCursor)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, payments_cursor: T.nilable(Shared::PaymentsCursor), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, payments_cursor: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @payments_cursor = payments_cursor
        @raw_response = raw_response
      end
    end
  end
end
