# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/listbalancesresponse'

module OpenApiSDK
  module Operations
    class ListBalancesRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

      sig { params(id: String).void }
      def initialize(id: nil)
        @id = id
      end
    end

    class ListBalancesResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Balances list
      field :list_balances_response, T.nilable(Shared::ListBalancesResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, list_balances_response: T.nilable(Shared::ListBalancesResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, list_balances_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @list_balances_response = list_balances_response
        @raw_response = raw_response
      end
    end
  end
end
