# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/listclientsresponse'

module OpenApiSDK
  module Operations
    class ListClientsResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # List of clients
      field :list_clients_response, T.nilable(Shared::ListClientsResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, list_clients_response: T.nilable(Shared::ListClientsResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, list_clients_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @list_clients_response = list_clients_response
        @raw_response = raw_response
      end
    end
  end
end
