# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/errorresponse'
require_relative '../shared/statsresponse'

module OpenApiSDK
  module Operations
    class ReadStatsRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # name of the ledger
      field :ledger, String, { 'path_param': { 'field_name': 'ledger', 'style': 'simple', 'explode': false } }

      sig { params(ledger: String).void }
      def initialize(ledger: nil)
        @ledger = ledger
      end
    end

    class ReadStatsResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Error
      field :error_response, T.nilable(Shared::ErrorResponse)
      field :raw_response, T.nilable(Faraday::Response)      # OK
      field :stats_response, T.nilable(Shared::StatsResponse)

      sig { params(content_type: String, status_code: Integer, error_response: T.nilable(Shared::ErrorResponse), raw_response: T.nilable(Faraday::Response), stats_response: T.nilable(Shared::StatsResponse)).void }
      def initialize(content_type: nil, status_code: nil, error_response: nil, raw_response: nil, stats_response: nil)
        @content_type = content_type
        @status_code = status_code
        @error_response = error_response
        @raw_response = raw_response
        @stats_response = stats_response
      end
    end
  end
end
