# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/readclientresponse'

module OpenApiSDK
  module Operations
    class ReadClientRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Client ID
      field :client_id, String, { 'path_param': { 'field_name': 'clientId', 'style': 'simple', 'explode': false } }

      sig { params(client_id: String).void }
      def initialize(client_id: nil)
        @client_id = client_id
      end
    end

    class ReadClientResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)      # Retrieved client
      field :read_client_response, T.nilable(Shared::ReadClientResponse)

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), read_client_response: T.nilable(Shared::ReadClientResponse)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, read_client_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @read_client_response = read_client_response
      end
    end
  end
end
