# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/response'

module OpenApiSDK
  module Operations
    class SearchResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)      # Success
      field :response, T.nilable(Shared::Response)

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), response: T.nilable(Shared::Response)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @response = response
      end
    end
  end
end
