# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/connector_enum'

module OpenApiSDK
  module Operations
    class UninstallConnectorRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # The name of the connector.
      field :connector, Shared::ConnectorEnum, { 'path_param': { 'field_name': 'connector', 'style': 'simple', 'explode': false } }

      sig { params(connector: Shared::ConnectorEnum).void }
      def initialize(connector: nil)
        @connector = connector
      end
    end

    class UninstallConnectorResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
      end
    end
  end
end
