# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/mapping'
require_relative '../shared/errorresponse'
require_relative '../shared/mappingresponse'

module OpenApiSDK
  module Operations
    class UpdateMappingRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Name of the ledger.
      field :ledger, String, { 'path_param': { 'field_name': 'ledger', 'style': 'simple', 'explode': false } }
      field :mapping, Shared::Mapping, { 'request': { 'media_type': 'application/json' } }

      sig { params(ledger: String, mapping: Shared::Mapping).void }
      def initialize(ledger: nil, mapping: nil)
        @ledger = ledger
        @mapping = mapping
      end
    end

    class UpdateMappingResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer      # Error
      field :error_response, T.nilable(Shared::ErrorResponse)      # OK
      field :mapping_response, T.nilable(Shared::MappingResponse)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, error_response: T.nilable(Shared::ErrorResponse), mapping_response: T.nilable(Shared::MappingResponse), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, error_response: nil, mapping_response: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @error_response = error_response
        @mapping_response = mapping_response
        @raw_response = raw_response
      end
    end
  end
end
