# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/updateclientrequest'
require_relative '../shared/updateclientresponse'

module OpenApiSDK
  module Operations
    class UpdateClientRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Client ID
      field :client_id, String, { 'path_param': { 'field_name': 'clientId', 'style': 'simple', 'explode': false } }
      field :update_client_request, T.nilable(Shared::UpdateClientRequest), { 'request': { 'media_type': 'application/json' } }

      sig { params(client_id: String, update_client_request: T.nilable(Shared::UpdateClientRequest)).void }
      def initialize(client_id: nil, update_client_request: nil)
        @client_id = client_id
        @update_client_request = update_client_request
      end
    end

    class UpdateClientResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)      # Updated client
      field :update_client_response, T.nilable(Shared::UpdateClientResponse)

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), update_client_response: T.nilable(Shared::UpdateClientResponse)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, update_client_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @update_client_response = update_client_response
      end
    end
  end
end
