# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/walletserrorresponse'

module OpenApiSDK
  module Operations
    class UpdateWalletRequestBody < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

            # Custom metadata to attach to this wallet.
      field :metadata, T.nilable(T::Hash[Symbol, Object]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('metadata') } }

      sig { params(metadata: T.nilable(T::Hash[Symbol, Object])).void }
      def initialize(metadata: nil)
        @metadata = metadata
      end
    end

    class UpdateWalletRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
      field :request_body, T.nilable(UpdateWalletRequestBody), { 'request': { 'media_type': 'application/json' } }

      sig { params(id: String, request_body: T.nilable(UpdateWalletRequestBody)).void }
      def initialize(id: nil, request_body: nil)
        @id = id
        @request_body = request_body
      end
    end

    class UpdateWalletResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :raw_response, T.nilable(Faraday::Response)      # Error
      field :wallets_error_response, T.nilable(Shared::WalletsErrorResponse)

      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), wallets_error_response: T.nilable(Shared::WalletsErrorResponse)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, wallets_error_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @wallets_error_response = wallets_error_response
      end
    end
  end
end
